openapi: 3.0.3
info:
  title: {{PROJECT_NAME}} API
  description: API documentation for {{PROJECT_NAME}}
  version: 0.1.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:4000
    description: Local development server
  - url: https://api.example.com
    description: Production server

tags:
  - name: Health
    description: Health check endpoints

paths:
  /api/health:
    get:
      tags:
        - Health
      summary: Basic health check
      description: Returns the health status of the API
      operationId: getHealth
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: API is running
                  timestamp:
                    type: string
                    format: date-time
                    example: '2025-10-24T10:30:00.000Z'

  /api/health/detailed:
    get:
      tags:
        - Health
      summary: Detailed health check
      description: Returns detailed health status including database connectivity
      operationId: getDetailedHealth
      responses:
        '200':
          description: All systems operational
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: All systems operational
                  timestamp:
                    type: string
                    format: date-time
                  services:
                    type: object
                    properties:
                      api:
                        type: string
                        example: healthy
                      database:
                        type: string
                        example: healthy
        '503':
          description: Service unavailable - some systems are down
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Some systems are down
                  timestamp:
                    type: string
                    format: date-time
                  services:
                    type: object
                    properties:
                      api:
                        type: string
                        example: healthy
                      database:
                        type: string
                        example: unhealthy

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT authentication token

  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Error message

# Add more endpoints and schemas as needed
